default:
  image: ${DOCKER_IMAGE}

stages:
  - build

build-code:
  stage: build
  script:
    - git clone --quiet --recursive https://${GIT_USERNAME}:${GIT_TOKEN}@git.ucsc.edu/${GIT_REPO}
    - cd ci/grading
    - ./setup.sh
    - cd ..
    - python3 ci.py
  timeout: 20 minutes
